# install python packages
---
- name: Install Docker Compose required python library
  pip:
    name:
      - docker
      - docker-pycreds
      - zipp
      - docker-compose
    state: latest
    extra_args: " --no-cache-dir "
    executable: pip3
  environment: "{{ proxy_env }}"
